### ISSUE TITLE
Input sanitization

### ISSUE THREAD

**Issue by victoriadrake** [victoriadrake/github-guestbook#8]
The current input sanitization (some [shell parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) that strips non-alphanumeric characters) is rather brutal. A better solution that maintains punctuation would be nice.

https://github.com/victoriadrake/github-guestbook/blob/4958ea5a89895d0e18c9d2610fc66d3320b236cd/create-comment.sh#L6

**Comment by MetRonnie** [comment]
How about using NodeJS and its `process.env`, which sanitises strings I believe? Something like:
```javascript
const fs = require('fs');

const commentHtml = `
<div class="comment">
  <p>${process.env.AUTHOR} says:</p>
  <p>${process.env.COMMENT}</p>
</div>
`;

fs.writeFile(`${process.env.FOLDER}/${process.env.ID}.html`, commentHtml);
```
Then
```yaml
- name: Turn comment into file
   run: node ./create-comment.js
```

**Comment by victoriadrake** [comment]
Please pardon my rusty JS; I tried your example and got:

```sh
fs.js:153
  throw new ERR_INVALID_CALLBACK(cb);
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
```

I also tried:

```js
const fs = require('fs')

const commentHtml = function () {
  return `
<div class="comment">
  <p>${process.env.AUTHOR} says:</p>
  <p>${process.env.COMMENT}</p>
</div>
`
}

fs.writeFile(`${process.env.FOLDER}/${process.env.ID}.html`, commentHtml)
```

I appreciate any tips folks might have!

**Comment by MetRonnie** [comment]
My bad. I've updated my solution (actually tested it this time!)

**Comment by victoriadrake** [comment]
Looks like this might work! I'll let folks fuzz test in production 😁 Thank you @MetRonnie!
